export const AppService = "https://mind-benders-2.azurewebsites.net/"
export const Endpoints = {
    "Login":"login",
    "Register":"register",
    "GetDocuments":"GetDocuments",
    "Get_income_sources":"Get_income_sources",
    "Get_Budgets":"Get_Budgets",
    "Get_Expenses":"Get_Expenses",
    "Get_ExpenseCategorys":"Get_ExpenseCategorys",
    "DeleteDocument":"DeleteDocument",
    "add_income_source":"add_income_source",
    "add_ExpenseCategory":"add_ExpenseCategory",
    "add_Budget":"add_Budget",
    "add_Expense":"add_Expense",
    "QAdocument":"QAdocument",
    "UploadDocument":"UploadDocument",
    "FinancialAssistant":"FinancialAssistant",
    "Get_InsuranceScheme":"Get_InsuranceScheme",
    "add_insurance_scheme":"add_insurance_scheme",
    "SummarizeDocument":"SummarizeDocument",
    "Get_InsuranceCategory":"Get_InsuranceCategory",
    "Get_insurance_schemeByID":"Get_insurance_scheme/",
    "QAInsuranceScheme":"QAInsuranceScheme",
    "downloadScheme":"downloadScheme/",
    "InsuranceAssistant":"InsuranceAssistant"
}